My_Resume/urls.py
from django.urls import path
from .views import *
app_name = "My_Resume"

urlpatterns = [
    path('',home_page,name='home'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('My_Resume.urls',namespace='resume'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

My_Resume/models.py
from django.db import models

# Create your models here.

My_Resume/views.py
from django.shortcuts import render

def home_page(request):
    return render(request, 'home.html',{})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    {% include "head.html" %}
    <title>{% block title %}{% endblock title %}</title>
</head>

<body class="theme-red">
  <div class="btn-back_to_top">
    <span class="ti-arrow-up"></span>
  </div>

  <div class="topbar-nav fixed-top">
    <div class="brand">
      <img src="{% static 'favicon.ico' %}" alt="" width="30" height="30">
    </div>
    <h3 class="ml-1">Gram</h3>
    <button class="btn-fab toggle-menu mr-3"><span class="ti-menu"></span></button>
  </div>

  {% include "nav_bar.html" %}
  {% block content %}{% endblock content %}
  {% include "footer.html" %}
  {% include "scripts.html" %}
</body>
{% include "style.html" %}
</html>

templates/footer.html
{% load static %}
 <!-- Footer -->
<div class="vg-footer footer" id="contact" style="margin-left: 30px;">
  <h1 class="text-center">Contact</h1>
  <hr>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 py-3">
        <div class="float-lg-right">
          <p>Where to find me</p>
          <hr class="divider">
          <p class="fs-large fg-white">Nasr City ,Cairo ,Egypt</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-3 py-3">
        <div class="float-lg-right">
          <p>Follow me</p>
          <hr class="divider">
          <ul class="list-unstyled">
            <li><a href="https://github.com/Hossamsaad99">GitHub</a></li>
            <li><a href="https://www.linkedin.com/in/hossam-saad-396108172/">LinkedIn</a></li>
            <li><a href="https://www.facebook.com/profile.php?id=100019072302541">Facebook</a></li>
            <li><a href="https://mobile.twitter.com/hossamsaad30">Twitter</a></li>

          </ul>
        </div>
      </div>
      <div class="col-md-6 col-lg-5 py-3">
        <div class="float-lg-right">
          <p>Contact me</p>
          <hr class="divider">
          <ul class="list-unstyled">
            <li>hossamsaad8090@gmail.com</li>
            <li>hossamhamed1999@gmail.com</li>
            <li>+(20)1221531209</li>

          </ul>
        </div>
      </div>
    </div>
    <div class="col-12">
      <p class="text-center tag mb-0 mt-4">Copyright &copy;2020. All right reserved | Software Engineering <span class="ti-heart fg-theme-red"></span> by <a href="https://www.macodeid.com/">Eng Hossam Saad</a></p>
    </div>
  </div>
</div> <!-- End footer -->

{% include "style.html" %}

templates/head.html
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="copyright" content="MACode ID, https://www.macodeid.com/">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/perfect-scrollbar/css/perfect-scrollbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/nice-select/css/nice-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fancybox/css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/virtual.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/minibar.virtual.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

templates/nav_bar.html
<!-- Minibar -->
<div class="minibar">
    <div class="header">
      <div class="brand"></div>
    </div>
    <div class="content">
      <ul class="main-menu">
        <li class="menu-item">
          <a href="{% url 'resume:home' %}" class="menu-link">
            <span class="icon ti-home"></span>
            <span class="caption">Home</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="#about" class="menu-link">
            <span class="icon ti-user"></span>
            <span class="caption">About</span>
          </a>
        </li>
        <li class="menu-item">
          <a href="#skill" class="menu-link">
            <span class="icon ti-support"></span>
            <span class="caption">Skills</span>
          </a>
        </li>
        
        <li class="menu-item">
          <a href="#portfolio" class="menu-link">
            <span class="icon ti-panel" style="font-size:35px;"></span>
            <span class="caption">Projects</span>
          </a>
        </li>
        
        <li class="menu-item">
          <a href="#achievements" class="menu-link">
            <span class="icon ti-medall" style="font-size:35px;"></span>
            <span class="caption">Achievements</span>
          </a>
        </li>
        
        <li class="menu-item">
          <a href="#blog" class="menu-link">
            <span class="icon ti-cup"></span>
            <span class="caption">My Certification</span>
          </a>
        </li>
        
        <li class="menu-item">
          <a href="#contact" class="menu-link">
            <span class="icon ti-email"></span>
            <span class="caption">Contact</span>
          </a>
        </li>

      </ul>
    </div>
</div>

<style>
  @media only screen and (max-width: 500px)  {
    .minibar
    {
        width:100%;
    }
    
  }
</style>

templates/scripts.html
{% load static %}

  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'vendor/owl-carousel/owl.carousel.min.js' %}"></script>

  <script src="{% static 'vendor/perfect-scrollbar/js/perfect-scrollbar.js' %}"></script>

  <script src="{% static 'vendor/isotope/isotope.pkgd.min.js' %}"></script>

  <script src="{% static 'vendor/nice-select/js/jquery.nice-select.min.js' %}"></script>

  <script src="{% static 'vendor/fancybox/js/jquery.fancybox.min.js' %}"></script>

  <script src="{% static 'vendor/wow/wow.min.js' %}"></script>

  <script src="{% static 'vendor/animateNumber/jquery.animateNumber.min.js' %}"></script>

  <script src="{% static 'vendor/waypoints/jquery.waypoints.min.js' %}"></script>

  <script src="{% static 'js/google-maps.js' %}"></script>

  <script src="{% static 'js/minibar-virtual.js' %}"></script>

  <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIA_zqjFMsJM_sxP9-6Pde5vVCTyJmUHM&callback=initMap"></script>

templates/style.html
<style>
@media only screen and (max-width: 700px) {
    
    .vg-footer 
    {
     text-align: center;
     left: -31px;
     width: 100%;
    }
    .vg-footer .divider
    {
      display: none;
    }
    .vg-footer .footer-info p
    {
      text-align: center;
    }
    .tag
    {
        text-align: center;
    }
   }
/* Extra small devices (phones, 600px and down) */
@media only screen and (max-width: 600px) {
 .vg-footer 
{
    text-align: center;
    left: -31px;
    width: 100%;
}
.vg-footer .divider
{
    display: none;
}
.vg-footer .footer-info p
{
    text-align: center;
}
.tag
{
    text-align: center;
}
}
/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 600px) {
    .vg-footer 
    {
    text-align: center;
    left: -31px;
    width: 100%;
    }
    .vg-footer .divider
    {
    display: none;
    }
    .vg-footer .footer-info p
    {
    text-align: center;
    }
    .tag
    {
        text-align: center;
    }
} 

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) {
    .vg-footer 
{
    text-align: center;
    left: -31px;
    width: 100%;
}
.vg-footer .divider
{
    display: none;
}
.vg-footer .footer-info p
{
    text-align: center;
}
.minibar
{
    width: 115px;
}
.tag
{
    text-align: center;
}
}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 992px) {
    .vg-footer 
{
    padding-left: 100px;
}
.minibar
{
    width: 115px;
}
}
 </style>
 